Switch to System.Text.Json
Particular/Particular.Approvals pull request #153
Opened 2023-03-09 13:29 UTC by danielmarbach

Alternative to #152

2023-03-13 20:27 UTC, bording requested changes

2023-03-13 20:27 UTC, bording commented on src/Particular.Approvals/Particular.Approvals.csproj
>      <PackageReference Include="NUnit" Version="[3.11.0, 4.0.0)" />
We should go ahead and update this to latest as well, though I guess that could be done in a separate PR.

2023-03-13 20:27 UTC, bording commented on src/Tests/Tests.csproj
> +    <TargetFrameworks>net462;net6.0;net7.0</TargetFrameworks>
```suggestion
    <TargetFrameworks>net472;net6.0;net7.0</TargetFrameworks>
```

2023-03-13 20:27 UTC, bording commented on src/Particular.Approvals/Particular.Approvals.csproj
> +    <TargetFrameworks>net462;netstandard2.0</TargetFrameworks>
If we're updating this and not worrying about older release branches, we might as well bump this up to `net472`.

```suggestion
    <TargetFrameworks>net472;netstandard2.0</TargetFrameworks>
```

2023-03-13 23:15 UTC, danielmarbach commented
@bording feel free to make those changes by directly pushing here. I'm 👍

2023-03-14 00:21 UTC, bording approved these changes

2023-03-14 10:32 UTC, merged